blank_issues_enabled: false
contact_links:
  - name: Discord community
    url: https://the-algorithms.com/discord/
    about: Have any questions or found any bugs? Contact us via our Discord community.
